name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Build the package & run pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pytest
        shell: bash -l {0}
        run: uv run pytest

  build_and_publish:
      name: Build and Publish to PyPI
      needs: test
      if: startsWith(github.ref, 'refs/tags/') && github.event.head_commit.message != '[skip ci]'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.9
          uses: actions/setup-python@v5
          with:
            python-version: "3.9"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install setuptools wheel
            python -m pip install twine
        - name: Build package
          run: |
            python -m pip install --upgrade pip
            pip install build
            python -m build
        - name: Publish distribution to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}